"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Users",
      [
        {
          first_name: "John",
          last_name: "Doe",
          email: "JohnDoe@gmail.com",
          username: "JohnD3664",
          password: "JoD!@#ff",
          address: "Jln Raya kenangan no 27",
          company: "JohnDoe-Corp",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Cherokee",
          last_name: "Cody",
          email: "cody_cherokee5658@outlook.com",
          username: "cherokee",
          password: "QLU82MJT6TA",
          address: "378-7923 Magna. Street",
          company: "Ante Vivamus Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Jorden",
          last_name: "Jenette",
          email: "jenette.jorden5626@aol.couk",
          username: "jorden4263",
          password: "HFJ55KLM6CE",
          address: "Ap #964-1760 Neque. Rd.",
          company: "Justo Nec Ante Institute",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Signe",
          last_name: "Xantha",
          email: "signexantha@icloud.org",
          username: "signe",
          password: "SJK83CHY4GD",
          address: "Ap #599-3798 Dis Avenue",
          company: "Lobortis Quam Incorporated",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Gil",
          last_name: "Sebastian",
          email: "gil-sebastian7827@outlook.edu",
          username: "gil5630",
          password: "WRD35IPA5DM",
          address: "P.O. Box 395, 2070 Leo. Av.",
          company: "Sem Nulla Interdum LLC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Blake",
          last_name: "Mohammad",
          email: "blake.mohammad@hotmail.net",
          username: "blake",
          password: "PYX88XLZ1QJ",
          address: "796-6432 Vitae St.",
          company: "Ut Quam Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Lucius",
          last_name: "George",
          email: "lgeorge@yahoo.couk",
          username: "lucius",
          password: "BKZ26KUA2LR",
          address: "Ap #953-2129 Luctus. Rd.",
          company: "Nulla Cras Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Ignatius",
          last_name: "Clinton",
          email: "iclinton430@hotmail.org",
          username: "ignatius356",
          password: "TWM81IDY3RQ",
          address: "3843 Vulputate, Av.",
          company: "Dictum Limited",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Avram",
          last_name: "Karina",
          email: "a_karina@yahoo.couk",
          username: "avram3697",
          password: "WXK75PLU1YT",
          address: "649-2064 Magnis St.",
          company: "Dui Lectus Foundation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Gisela",
          last_name: "Camden",
          email: "camden_gisela@protonmail.couk",
          username: "gisela",
          password: "NEW32OTN8PW",
          address: "880-1457 Mi Ave",
          company: "Velit Justo Nec Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Bruce",
          last_name: "Jane",
          email: "jane-bruce@icloud.com",
          username: "bruce",
          password: "HGO83GIU1YR",
          address: "Ap #755-6564 Elit Rd.",
          company: "Metus In Industries",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Amaya",
          last_name: "Ethan",
          email: "e-amaya3029@protonmail.com",
          username: "amaya",
          password: "IUU82WMQ8SS",
          address: "644-1288 Morbi St.",
          company: "Sed Pede Institute",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Ignacia",
          last_name: "Jermaine",
          email: "ignacia.jermaine@yahoo.org",
          username: "ignacia",
          password: "RCC35CKU6FN",
          address: "218-7501 Mauris. St.",
          company: "Mi Tempor Corporation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Deborah",
          last_name: "Xaviera",
          email: "d_xaviera9157@outlook.ca",
          username: "deborah9569",
          password: "OFZ04RUP4QO",
          address: "633-3841 Tempus Avenue",
          company: "Ac Incorporated",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Vanna",
          last_name: "Maris",
          email: "vanna.maris291@protonmail.net",
          username: "vanna1359",
          password: "TPT31NOH4TX",
          address: "323-2498 Vehicula St.",
          company: "Amet Industries",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Gabriel",
          last_name: "Clio",
          email: "clio-gabriel7255@icloud.org",
          username: "gabriel5362",
          password: "PIB17DLA7EJ",
          address: "6348 Odio Av.",
          company: "Ante Bibendum LLC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Slade",
          last_name: "Nissim",
          email: "nissim.slade7168@icloud.edu",
          username: "slade",
          password: "ICB64CNS8UD",
          address: "P.O. Box 671, 7698 Parturient Av.",
          company: "Nec Ligula Foundation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Rahim",
          last_name: "Lydia",
          email: "rahim.lydia@yahoo.com",
          username: "rahim5475",
          password: "FRV71VRP2LN",
          address: "1625 Ut, Avenue",
          company: "Donec Industries",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Piper",
          last_name: "Daniel",
          email: "danielpiper@hotmail.edu",
          username: "piper1750",
          password: "BVD21AOV3IY",
          address: "Ap #765-273 Donec St.",
          company: "Bibendum Sed Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Leonard",
          last_name: "Willow",
          email: "willow.leonard6048@google.ca",
          username: "leonard",
          password: "TXL28ELX2GZ",
          address: "Ap #288-9467 Non St.",
          company: "Aliquet Proin Foundation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Jillian",
          last_name: "Marcia",
          email: "marciajillian7495@outlook.com",
          username: "jillian",
          password: "TDO72QDV2IL",
          address: "610-9648 Rhoncus. Street",
          company: "Magna Phasellus Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Gil",
          last_name: "Vance",
          email: "vance-gil9897@icloud.couk",
          username: "gil5153",
          password: "ILL94HLJ8TE",
          address: "Ap #455-7040 Sit Rd.",
          company: "Integer Vitae Industries",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Jolene",
          last_name: "Patrick",
          email: "patrickjolene3351@outlook.net",
          username: "jolene210",
          password: "KFR56QXX5HM",
          address: "2533 Fringilla St.",
          company: "Risus Varius Orci Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Hammett",
          last_name: "Mikayla",
          email: "hammett.mikayla@aol.org",
          username: "hammett849",
          password: "NBH68YLL4SJ",
          address: "Ap #460-339 Quis Street",
          company: "Duis At Lacus PC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Ronan",
          last_name: "Wylie",
          email: "rwylie4163@yahoo.com",
          username: "ronan4751",
          password: "GED66VXL8OH",
          address: "3409 Nascetur St.",
          company: "Mi Fringilla Foundation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Colt",
          last_name: "Gloria",
          email: "g_colt4082@outlook.couk",
          username: "colt",
          password: "YOP68CPS6UE",
          address: "Ap #698-7592 Nulla Rd.",
          company: "Non Egestas Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Eliana",
          last_name: "Justina",
          email: "e-justina1428@hotmail.org",
          username: "eliana",
          password: "TQL23QUV2XX",
          address: "Ap #763-7173 Ornare, Avenue",
          company: "Nisl Nulla Eu Industries",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Clinton",
          last_name: "Jamal",
          email: "jamal-clinton@yahoo.com",
          username: "clinton",
          password: "YBV23STU3FG",
          address: "P.O. Box 101, 5403 Placerat St.",
          company: "Morbi Vehicula Pellentesque Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Uriel",
          last_name: "Lana",
          email: "u.lana@protonmail.couk",
          username: "uriel4148",
          password: "VBP32CGW7QL",
          address: "Ap #150-8188 At, Avenue",
          company: "Sed Sem Limited",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Vivian",
          last_name: "Kenyon",
          email: "vivian_kenyon@protonmail.com",
          username: "vivian",
          password: "XOK22DXL2YV",
          address: "Ap #150-9855 Senectus Street",
          company: "Tincidunt Dui Limited",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Caleb",
          last_name: "Hedy",
          email: "hedy.caleb@icloud.couk",
          username: "caleb",
          password: "HBJ67SQT0EP",
          address: "9252 Mauris Avenue",
          company: "Molestie Pharetra Industries",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Len",
          last_name: "Jada",
          email: "len_jada8547@icloud.com",
          username: "len",
          password: "CNQ65TJU8IZ",
          address: "P.O. Box 954, 5371 Dictum Avenue",
          company: "Risus LLC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Elton",
          last_name: "Ori",
          email: "ori_elton@icloud.net",
          username: "elton2708",
          password: "MUA44GUH8LE",
          address: "Ap #234-7349 Eu Avenue",
          company: "Nunc Est Institute",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Devin",
          last_name: "Nehru",
          email: "devinnehru@protonmail.net",
          username: "devin",
          password: "YLE45FJV2QW",
          address: "Ap #173-375 Pulvinar Rd.",
          company: "Pede Cum PC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Florence",
          last_name: "Channing",
          email: "f.channing@icloud.com",
          username: "florence",
          password: "CVC84ISE7TY",
          address: "Ap #713-7803 Eleifend, Street",
          company: "Sit Amet Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Kerry",
          last_name: "Lesley",
          email: "l-kerry@hotmail.edu",
          username: "kerry6309",
          password: "MHS72YHK1HS",
          address: "Ap #121-4445 Vulputate, Av.",
          company: "Et Rutrum Eu Industries",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Cullen",
          last_name: "Elliott",
          email: "elliott.cullen@google.edu",
          username: "cullen7382",
          password: "HTH31XIQ1RK",
          address: "Ap #205-1799 Quisque St.",
          company: "Senectus Et Inc.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Donna",
          last_name: "Skyler",
          email: "skyler_donna1847@icloud.couk",
          username: "donna",
          password: "HCM82DRF2NS",
          address: "Ap #960-7175 Aliquet Av.",
          company: "Eleifend Cras PC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Richard",
          last_name: "Lani",
          email: "richard-lani@aol.org",
          username: "richard5247",
          password: "RQZ83FOU4BU",
          address: "P.O. Box 806, 4031 At Av.",
          company: "Tincidunt Dui Augue Foundation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Iris",
          last_name: "Adrian",
          email: "adrian_iris@yahoo.net",
          username: "iris",
          password: "QIB88VKY7HM",
          address: "Ap #518-8397 Mi Avenue",
          company: "Pretium Foundation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Hamilton",
          last_name: "Denise",
          email: "d.hamilton@google.org",
          username: "hamilton",
          password: "JGM49VYL4BI",
          address: "2338 Luctus. Road",
          company: "Phasellus In Corp.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Griffith",
          last_name: "Ila",
          email: "griffith.ila1344@protonmail.edu",
          username: "griffith2433",
          password: "QHM77RIC9CP",
          address: "Ap #818-2087 Velit. Road",
          company: "Lacus Varius Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Petra",
          last_name: "Demetrius",
          email: "petra_demetrius@google.com",
          username: "petra",
          password: "FKE49SKD6GS",
          address: "166-7074 Ornare. Avenue",
          company: "Et Pede Nunc Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Samson",
          last_name: "Penelope",
          email: "s_penelope9332@icloud.org",
          username: "samson6774",
          password: "ETE63SSH5MQ",
          address: "Ap #718-1780 Duis Street",
          company: "Tempus Lorem Institute",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Halla",
          last_name: "Cadman",
          email: "c-halla@icloud.ca",
          username: "halla4189",
          password: "MSE55MSW5TS",
          address: "913-9482 Sed St.",
          company: "Vulputate Velit Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Dieter",
          last_name: "Castor",
          email: "dieter_castor4690@aol.edu",
          username: "dieter",
          password: "UWB76UIS8ON",
          address: "Ap #309-5228 Pellentesque Avenue",
          company: "Sed Id Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Serina",
          last_name: "Mira",
          email: "mira.serina@protonmail.net",
          username: "serina7965",
          password: "FAN87JLK1TR",
          address: "359-9322 Odio, St.",
          company: "Ante LLC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Savannah",
          last_name: "Holmes",
          email: "holmes.savannah5631@aol.couk",
          username: "savannah8757",
          password: "NTB88NUF2UU",
          address: "471-3346 Vivamus Street",
          company: "In Scelerisque Scelerisque Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Gabriel",
          last_name: "Dorian",
          email: "gabriel-dorian@outlook.edu",
          username: "gabriel1413",
          password: "BYK39ZHW5UT",
          address: "Ap #790-138 Sit Avenue",
          company: "Lacinia Mattis Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "MacKenzie",
          last_name: "Mercedes",
          email: "mackenzie.mercedes@aol.com",
          username: "mackenzie5838",
          password: "XRG55TIN6RN",
          address: "Ap #445-7143 Tellus Rd.",
          company: "Id Blandit Limited",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Mallory",
          last_name: "Alec",
          email: "alec.mallory2942@hotmail.edu",
          username: "mallory",
          password: "IJK30OYX2MJ",
          address: "Ap #269-6611 Nec, St.",
          company: "Vehicula Et Industries",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Ciaran",
          last_name: "Aurelia",
          email: "aureliaciaran@outlook.ca",
          username: "ciaran",
          password: "CCE77EZF7YB",
          address: "359 Nisl. St.",
          company: "Fusce LLC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Jena",
          last_name: "Sebastian",
          email: "sjena@yahoo.ca",
          username: "jena",
          password: "EJX33TCP5TL",
          address: "640-1245 Rutrum Rd.",
          company: "Sit Industries",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Darius",
          last_name: "Grant",
          email: "dgrant@protonmail.org",
          username: "darius9764",
          password: "KTY31HJB1ME",
          address: "Ap #718-298 Commodo Ave",
          company: "Mollis Vitae PC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Erin",
          last_name: "Darius",
          email: "dariuserin7978@icloud.net",
          username: "erin",
          password: "JHB34QST8CL",
          address: "8591 Luctus St.",
          company: "Lorem LLC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Victor",
          last_name: "Eagan",
          email: "eagan-victor@icloud.ca",
          username: "victor9485",
          password: "JIC43TWJ1IY",
          address: "Ap #972-2017 Non Av.",
          company: "Mollis Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Mona",
          last_name: "Tara",
          email: "mtara2275@protonmail.couk",
          username: "mona",
          password: "KGS17LBK2CE",
          address: "P.O. Box 553, 3383 Duis Road",
          company: "Hymenaeos Mauris Corporation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Lester",
          last_name: "Jonah",
          email: "jonah.lester@hotmail.org",
          username: "lester",
          password: "UDD81BHQ2FQ",
          address: "Ap #459-4024 Vivamus Rd.",
          company: "Ultrices Sit LLP",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Ferris",
          last_name: "Russell",
          email: "russell_ferris@icloud.org",
          username: "ferris56",
          password: "SFC21XWL4FG",
          address: "665-8663 Eu Av.",
          company: "Nec Urna LLP",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Simon",
          last_name: "Galena",
          email: "galena-simon6051@outlook.ca",
          username: "simon8866",
          password: "KJT54YUS9XU",
          address: "592-5266 Libero Ave",
          company: "Arcu Ac Orci Limited",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Lev",
          last_name: "Isaac",
          email: "isaac-lev@aol.edu",
          username: "lev",
          password: "CZC95KFL2IK",
          address: "517-9265 Lacinia Av.",
          company: "Dictum Sapien LLP",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Debra",
          last_name: "Vanna",
          email: "v_debra3449@icloud.couk",
          username: "debra7319",
          password: "DQY89JLI8AA",
          address: "191-124 Scelerisque Av.",
          company: "Nisl Nulla PC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Garrison",
          last_name: "Hammett",
          email: "hgarrison5608@yahoo.ca",
          username: "garrison",
          password: "ZKI84SNH2LP",
          address: "327-7492 Egestas Rd.",
          company: "Ante Vivamus Non Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Regan",
          last_name: "Odysseus",
          email: "regan.odysseus@aol.ca",
          username: "regan",
          password: "RMP13JZC7DY",
          address: "808-8930 Consequat Rd.",
          company: "Consectetuer Rhoncus Institute",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Joel",
          last_name: "Michael",
          email: "j_michael7918@icloud.edu",
          username: "joel6318",
          password: "LEZ17UER5XM",
          address: "Ap #523-5212 Nascetur Road",
          company: "Diam Dictum Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Martha",
          last_name: "Wyoming",
          email: "wyoming_martha651@hotmail.couk",
          username: "martha",
          password: "YLR25BFY5ZO",
          address: "P.O. Box 431, 9974 Mi Road",
          company: "Ut Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Warren",
          last_name: "Quinn",
          email: "warren-quinn896@outlook.net",
          username: "warren2506",
          password: "ZJU59TXK0UG",
          address: "Ap #977-2008 In Av.",
          company: "Enim Mauris Corp.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Olga",
          last_name: "Lesley",
          email: "o_lesley@icloud.org",
          username: "olga530",
          password: "OLK31RHB3EX",
          address: "P.O. Box 469, 3381 Quis Ave",
          company: "Nisl Quisque Fringilla Corporation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Tamara",
          last_name: "Rafael",
          email: "t-rafael@outlook.edu",
          username: "tamara",
          password: "KQX71FRM7TM",
          address: "Ap #197-965 Commodo Road",
          company: "Porttitor Industries",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Jermaine",
          last_name: "Kato",
          email: "k.jermaine@aol.com",
          username: "jermaine",
          password: "SGS99BPJ1EA",
          address: "P.O. Box 712, 1762 Nisi Street",
          company: "Vulputate Dui Nec Foundation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Natalie",
          last_name: "Wang",
          email: "nwang1156@google.ca",
          username: "natalie",
          password: "UCB34ONP1WJ",
          address: "498-7155 Nunc Street",
          company: "Adipiscing Foundation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Arsenio",
          last_name: "Roary",
          email: "roary-arsenio1339@protonmail.org",
          username: "arsenio",
          password: "KKH31AOA2EV",
          address: "P.O. Box 209, 8249 Ut St.",
          company: "Non Hendrerit Id Corporation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Donovan",
          last_name: "Xanthus",
          email: "xanthus-donovan@hotmail.org",
          username: "donovan",
          password: "GLU51FNS7YK",
          address: "552-4556 Neque Av.",
          company: "Sapien PC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Connor",
          last_name: "Dalton",
          email: "connor.dalton6923@icloud.org",
          username: "connor2552",
          password: "CNP89CCH7WR",
          address: "7144 Euismod Rd.",
          company: "Eget Tincidunt Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Daphne",
          last_name: "Acton",
          email: "acton-daphne523@hotmail.couk",
          username: "daphne",
          password: "DNU35SSH6PT",
          address: "P.O. Box 401, 7813 Dictum St.",
          company: "Neque LLC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Hannah",
          last_name: "India",
          email: "h-india6279@icloud.net",
          username: "hannah",
          password: "LRG46LXR9CY",
          address: "607-5013 Molestie Rd.",
          company: "Lectus Company",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Ingrid",
          last_name: "Bert",
          email: "i_bert4587@aol.org",
          username: "ingrid",
          password: "BUU24BII8QS",
          address: "593-8118 Elit. Rd.",
          company: "Elementum Lorem PC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Zeus",
          last_name: "Audrey",
          email: "z_audrey2738@aol.org",
          username: "zeus9160",
          password: "FQX87VDJ3HR",
          address: "P.O. Box 955, 7174 Penatibus St.",
          company: "Amet Nulla Corporation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Portia",
          last_name: "Lana",
          email: "p_lana1441@outlook.net",
          username: "portia",
          password: "QQP85GRJ1LO",
          address: "453-9008 Porttitor Ave",
          company: "Imperdiet LLP",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Damian",
          last_name: "Odessa",
          email: "odessa_damian5660@protonmail.net",
          username: "damian2306",
          password: "TUL46CKQ3KX",
          address: "286-1241 Adipiscing. Avenue",
          company: "Lectus Pede Limited",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Jameson",
          last_name: "Baker",
          email: "baker_jameson3420@google.net",
          username: "jameson",
          password: "GGQ63GJS9QU",
          address: "137-4993 At, Av.",
          company: "Proin Ultrices Duis Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Ivan",
          last_name: "Judah",
          email: "i.judah6333@hotmail.com",
          username: "ivan4083",
          password: "HIR33GVY3HP",
          address: "220-5603 Scelerisque Avenue",
          company: "Velit Foundation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Odette",
          last_name: "Hilary",
          email: "odettehilary@hotmail.edu",
          username: "odette6236",
          password: "IUP36UJM2YL",
          address: "Ap #821-6344 Euismod Ave",
          company: "Lobortis Quam A Inc.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Julie",
          last_name: "Chava",
          email: "cjulie9929@protonmail.net",
          username: "julie",
          password: "UWQ92UQV6HA",
          address: "580-669 Porttitor St.",
          company: "Egestas A Limited",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Quamar",
          last_name: "Brady",
          email: "b.quamar2871@aol.org",
          username: "quamar5347",
          password: "IMF62XSX7XK",
          address: "683-2005 Dis Street",
          company: "Malesuada Fames Foundation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Rosalyn",
          last_name: "Kathleen",
          email: "r-kathleen@aol.edu",
          username: "rosalyn7029",
          password: "OGZ74LUZ3FT",
          address: "Ap #242-3638 Vitae St.",
          company: "Ante Nunc Mauris Company",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Giacomo",
          last_name: "Alice",
          email: "giacomo-alice@icloud.org",
          username: "giacomo7127",
          password: "YOQ72TSP4DS",
          address: "398-1761 Vulputate, St.",
          company: "Vivamus Ltd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Felix",
          last_name: "Hall",
          email: "f-hall3601@yahoo.net",
          username: "felix7799",
          password: "ICG44RHT3OZ",
          address: "Ap #625-6129 Pede, Road",
          company: "Aenean Massa Inc.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Griffith",
          last_name: "Yvette",
          email: "g_yvette3694@protonmail.edu",
          username: "griffith",
          password: "CXN83PWX7NY",
          address: "775-1365 Lacus Rd.",
          company: "Mauris A Inc.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Hermione",
          last_name: "Maile",
          email: "mailehermione7864@icloud.org",
          username: "hermione4719",
          password: "RJT87BLK2JY",
          address: "414-5342 Sit St.",
          company: "Adipiscing Elit LLC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Flynn",
          last_name: "Reuben",
          email: "flynn-reuben7131@icloud.couk",
          username: "flynn1133",
          password: "IBV87RXJ9TC",
          address: "Ap #914-4164 Enim Rd.",
          company: "Nec Inc.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Kyra",
          last_name: "Elaine",
          email: "kyra_elaine@aol.ca",
          username: "kyra1352",
          password: "OES75GLN4WL",
          address: "P.O. Box 143, 4646 Orci Av.",
          company: "Donec Sollicitudin Limited",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Eagan",
          last_name: "Rhoda",
          email: "erhoda@yahoo.net",
          username: "eagan8552",
          password: "TRE01OPX6DC",
          address: "6070 Urna Rd.",
          company: "Vel Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Selma",
          last_name: "Jaquelyn",
          email: "j-selma@hotmail.couk",
          username: "selma6053",
          password: "XHN64BZB4EW",
          address: "Ap #715-2481 Amet Rd.",
          company: "Dolor PC",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Echo",
          last_name: "Jelani",
          email: "e-jelani1429@aol.couk",
          username: "echo2826",
          password: "RXU14LUR5UE",
          address: "8762 Amet St.",
          company: "Eu Ultrices Incorporated",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Keane",
          last_name: "Adara",
          email: "kadara2596@protonmail.couk",
          username: "keane",
          password: "NKW83DKQ9BC",
          address: "P.O. Box 805, 9336 Vestibulum Av.",
          company: "Montes Nascetur Ridiculus Associates",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Isadora",
          last_name: "Gail",
          email: "gail.isadora6706@icloud.com",
          username: "isadora2699",
          password: "QSG73RMO1OD",
          address: "Ap #506-6074 Non Rd.",
          company: "Egestas A Incorporated",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Keith",
          last_name: "Adrian",
          email: "a.keith1390@hotmail.com",
          username: "keith2580",
          password: "JBQ14HNJ6LY",
          address: "353-1249 Ligula. Road",
          company: "Mi Fringilla Corporation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Fredericka",
          last_name: "Wilma",
          email: "fredericka.wilma@google.org",
          username: "fredericka",
          password: "BRQ24QPU7ZI",
          address: "343-8037 Tincidunt Av.",
          company: "Et Ultrices Consulting",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "May",
          last_name: "Xavier",
          email: "xavier-may@aol.couk",
          username: "may",
          password: "GTC72XBK7CX",
          address: "Ap #580-6308 Enim. St.",
          company: "Mi Ac Corp.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          first_name: "Lunea",
          last_name: "Georgia",
          email: "l_georgia8334@icloud.org",
          username: "lunea",
          password: "TMO86QGL7XK",
          address: "P.O. Box 811, 8498 Dui. St.",
          company: "Dolor Donec Corporation",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Users", null, {restartIdentity: true ,truncate: true, cascade: true});
  },
};
